spring:
  profiles:
    active: dev


---
server:
  port: 2000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/ #指向注册中心地址
  instance:
    prefer-ip-address: true  #使用ip注册到注册中心
spring:
  application:
    name: AIGOU_PLAT
  profiles: dev

---
server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/ #指向注册中心地址
  instance:
    prefer-ip-address: true  #使用ip注册到注册中心
spring:
  application:
    name: AIGOU_PLAT
  profiles: test
