spring:
  profiles:
    active: dev


---
server:
  port: 2000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_PLAT
  profiles: dev

---
server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_PLAT
  profiles: test
